#!/bin/bash
IslandsIconUrl=$(curl --cookie ".ROBLOSECURITY=$RBX_AUTH" https://thumbnails.roblox.com/v1/places/gameicons\?placeIds\=4872321990\&returnPolicy\=ForceAutoGenerated\&size\=256x256\&format\=Png\&isCircular\=false | jq -j '.data[0].imageUrl')
curl $IslandsIconUrl > assets/islands-icon.png

ZenerithIconUrl=$(curl --cookie ".ROBLOSECURITY=$RBX_AUTH" https://thumbnails.roblox.com/v1/places/gameicons\?placeIds\=6889068401\&returnPolicy\=ForceAutoGenerated\&size\=256x256\&format\=Png\&isCircular\=false | jq -j '.data[0].imageUrl')
curl $ZenerithIconUrl > assets/zenerith-icon.png
